components:
  schemas:
    RedfishError:
      description: The error payload from a Redfish service.
      properties:
        error:
          description: The properties that describe an error from a Redfish service.
          properties:
            '@Message.ExtendedInfo':
              description: An array of messages describing one or more error messages.
              items:
                $ref: Message.v1_2_1.yaml#/components/schemas/Message_v1_2_1_Message
              type: array
              x-longDescription: This property shall be an array of message objects
                describing one or more error messages.
            code:
              description: A string indicating a specific `MessageId` from a message
                registry.
              readOnly: true
              type: string
              x-longDescription: This property shall contain a string indicating a
                specific `MessageId` from a message registry.
            message:
              description: A human-readable error message corresponding to the message
                in a message registry.
              readOnly: true
              type: string
              x-longDescription: This property shall contain a human-readable error
                message corresponding to the message in a message registry.
          required:
          - code
          - message
          type: object
          x-longDescription: The Redfish Specification-described type shall contain
            properties that describe an error from a Redfish service.
      required:
      - error
      type: object
      x-longDescription: The Redfish Specification-described type shall contain an
        error payload from a Redfish service.
info:
  contact:
    name: DMTF
    url: https://www.dmtf.org/standards/redfish
  description: This contains the definition of a Redfish service.
  title: Redfish
  version: '2025.3'
  x-copyright: Copyright 2025 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
openapi: 3.0.1
paths:
  /redfish/v1/:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ServiceRoot.v1_19_0.yaml#/components/schemas/ServiceRoot_v1_19_0_ServiceRoot
          description: The response contains a representation of the ServiceRoot resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
  /redfish/v1/$metadata:
    get:
      responses:
        '200':
          content:
            application/xml: {}
          description: OData $metadata.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
  /redfish/v1/Systems:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ComputerSystemCollection.yaml#/components/schemas/ComputerSystemCollection_ComputerSystemCollection
          description: The response contains a representation of the ComputerSystemCollection
            resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
  /redfish/v1/Systems/{ComputerSystemId}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ComputerSystem.v1_26_0.yaml#/components/schemas/ComputerSystem_v1_26_0_ComputerSystem
          description: The response contains a representation of the ComputerSystem
            resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
    parameters:
    - description: The value of the Id property of the ComputerSystem resource
      in: path
      name: ComputerSystemId
      required: true
      schema:
        type: string
  /redfish/v1/Systems/{ComputerSystemId}/Actions/ComputerSystem.Reset:
    parameters:
    - description: The value of the Id property of the ComputerSystem resource
      in: path
      name: ComputerSystemId
      required: true
      schema:
        type: string
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: ComputerSystem.v1_26_0.yaml#/components/schemas/ComputerSystem_v1_26_0_ResetRequestBody
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: The response contains the results of the Reset action
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition